package br.com.ufmg.coltec.locamais.ui.constant;

public interface SystemRoute {

    String HISTORICO_LOCACAO = "HISTORICO_LOCACAO";
    String FINALIZAR_LOCACAO = "FINALIZAR_LOCACAO";
    String LISTAR_LOCACOES = "LISTAR_LOCACOES";
    String FAZER_LOCACAO = "FAZER_LOCACAO";
    String AUTENTICACAO_PANEL = "AUTENTICACAO_PANEL";
    String FUNCIONARIO_DESCRICAO_PANEL = "FUNCIONARIO_DESCRICAO_PANEL";
    String CLIENTE_FORMULARIO_CADASTRO = "CLIENTE_FORMULARIO_CADASTRO";
    String CLIENTE_LISTAR = "CLIENTE_LISTAR";
    String FUNCIONARIO_FORMULARIO_CADASTRO = "FUNCIONARIO_FORMULARIO_CADASTRO";
    String FABRICANTE_FORMULARIO_CADASTRO = "FABRICANTE_FORMULARIO_CADASTRO";
    String VEICULO_FORMULARIO_CADASTRO = "VEICULO_FORMULARIO_CADASTRO";
    String LISTAR_VEICULOS = "LISTAR_VEICULOS";
}
